import styled from 'styled-components'

export const Page = styled.div`width: min(100%, 1200px); margin: 0 auto;`
export const Header = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 24px; @media (max-width: 560px) { flex-direction: column; }`
export const Title = styled.h1`margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 32px; line-height: 40px;`
export const Subtitle = styled.p`margin: 6px 0 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 15px;`
export const EditButton = styled.button`min-height: 46px; border: 1px solid ${({ theme }) => theme.colors.brand.strong}; border-radius: 12px; padding: 12px 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.brand.strong}; cursor: pointer; font-weight: 600;`
export const State = styled.p`padding: 64px 0; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const ProfileCard = styled.section`display: grid; gap: 24px; grid-template-columns: minmax(0, 1fr) 280px; align-items: center; border-radius: 28px; padding: 32px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; @media (max-width: 760px) { grid-template-columns: 1fr; padding: 24px; }`
export const ProfileHero = styled.div`display: flex; align-items: center; gap: 24px; img { width: 112px; height: 112px; border-radius: 50%; object-fit: cover; } h2 { margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 26px; } p { margin: 6px 0 12px; color: ${({ theme }) => theme.colors.brand.primary}; font-size: 14px; font-weight: 600; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 14px; line-height: 1.6; } @media (max-width: 480px) { align-items: flex-start; flex-direction: column; }`
export const Stats = styled.div`display: grid; gap: 12px; grid-template-columns: repeat(3, 1fr); > div { display: flex; flex-direction: column; align-items: center; gap: 6px; border-radius: 16px; padding: 16px 8px; background: ${({ theme }) => theme.colors.background.muted}; } strong { color: ${({ theme }) => theme.colors.brand.strong}; font-size: 24px; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
export const Section = styled.section`margin-top: 32px;`
export const SectionTitle = styled.h2`margin: 0 0 12px; color: ${({ theme }) => theme.colors.text.strong}; font-size: 18px;`
export const RecentGrid = styled.div`display: grid; gap: 16px; grid-template-columns: repeat(3, minmax(0, 1fr)); @media (max-width: 700px) { grid-template-columns: 1fr; }`
export const RecentTrip = styled.button`overflow: hidden; border: 0; border-radius: 20px; padding: 0 0 16px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; text-align: left; img { display: block; width: 100%; height: 128px; object-fit: cover; } strong, span { display: block; padding-inline: 16px; } strong { padding-top: 12px; font-size: 15px; } span { padding-top: 4px; color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
export const Empty = styled.p`grid-column: 1 / -1; margin: 0; padding: 32px; border-radius: 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const SettingsCard = styled.section`border-radius: 20px; padding: 8px 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle};`
export const SettingsButton = styled.button`display: flex; width: 100%; align-items: center; justify-content: space-between; border: 0; border-bottom: 1px solid ${({ theme }) => theme.colors.border.subtle}; padding: 18px 0; background: transparent; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; font-size: 14px; text-align: left; &:last-child { border-bottom: 0; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 20px; }`
