import styled from 'styled-components'

export const Page = styled.div`width: min(100%, 1200px); margin: 0 auto;`
export const Header = styled.header`display: flex; flex-direction: column; gap: 6px; margin-bottom: 24px;`
export const Title = styled.h1`margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 32px; line-height: 40px;`
export const Subtitle = styled.p`margin: 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 15px;`
export const Error = styled.p`margin: 0 0 16px; color: ${({ theme }) => theme.colors.status.error}; font-size: 14px;`
export const State = styled.p`padding: 64px 0; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const CardGrid = styled.div`display: grid; gap: 24px; grid-template-columns: repeat(3, minmax(0, 1fr)); @media (max-width: 900px) { grid-template-columns: repeat(2, minmax(0, 1fr)); } @media (max-width: 560px) { grid-template-columns: 1fr; }`
export const TripCard = styled.button`overflow: hidden; border: 0; border-radius: 28px; padding: 0 0 20px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; text-align: left; img { display: block; width: 100%; height: 170px; object-fit: cover; } strong, span, small { display: block; padding-inline: 20px; } strong { padding-top: 16px; font-size: 18px; } span { padding-top: 6px; color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; } small { padding-top: 12px; color: ${({ theme }) => theme.colors.brand.strong}; font-size: 12px; font-weight: 600; }`
export const AddCard = styled.button`display: grid; min-height: 318px; place-items: center; border: 1px dashed ${({ theme }) => theme.colors.brand.primary}; border-radius: 28px; background: ${({ theme }) => theme.colors.background.muted}; color: ${({ theme }) => theme.colors.brand.strong}; cursor: pointer; font-size: 16px; font-weight: 600;`
export const Empty = styled.p`grid-column: 1 / -1; margin: 0; padding: 64px; border-radius: 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const StepCard = styled.section`display: flex; min-height: 360px; flex-direction: column; align-items: flex-start; gap: 16px; border-radius: 28px; padding: 32px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; h2 { margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 24px; } p { margin: 0; color: ${({ theme }) => theme.colors.text.muted}; line-height: 1.6; } @media (max-width: 560px) { padding: 24px; }`
export const StepNumber = styled.span`color: ${({ theme }) => theme.colors.brand.primary}; font-size: 12px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;`
export const ActionRow = styled.div`display: flex; flex-wrap: wrap; gap: 8px; margin-top: auto;`
export const MemberList = styled.div`display: flex; width: 100%; flex-direction: column; gap: 8px;`
export const Member = styled.div<{ disabled?: boolean }>`display: flex; align-items: center; justify-content: space-between; border: 1px solid ${({ theme }) => theme.colors.border.soft}; border-radius: 12px; padding: 16px; color: ${({ theme }) => theme.colors.text.strong}; opacity: ${({ disabled }) => (disabled ? 0.6 : 1)}; span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
export const FormGrid = styled.div`display: grid; width: 100%; gap: 16px; grid-template-columns: repeat(2, minmax(0, 1fr)); @media (max-width: 560px) { grid-template-columns: 1fr; }`
export const Field = styled.label`display: flex; flex-direction: column; gap: 6px; color: ${({ theme }) => theme.colors.text.strong}; font-size: 13px; font-weight: 600; select { height: 46px; border: 1px solid ${({ theme }) => theme.colors.border.default}; border-radius: 12px; padding: 0 12px; background: ${({ theme }) => theme.colors.background.soft}; color: ${({ theme }) => theme.colors.text.strong}; }`
export const ExploreGrid = styled.div`display: grid; gap: 24px; grid-template-columns: repeat(3, minmax(0, 1fr)); @media (max-width: 700px) { grid-template-columns: 1fr; }`
export const CategoryCard = styled.button`display: flex; min-height: 180px; flex-direction: column; align-items: flex-start; justify-content: flex-end; gap: 8px; border: 0; border-radius: 28px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; text-align: left; span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; } b { align-self: flex-end; color: ${({ theme }) => theme.colors.brand.primary}; font-size: 24px; }`
export const VoteCategoryRow = styled.div`display: flex; flex-wrap: wrap; gap: 8px; margin: 16px 0;`
export const VoteCategoryButton = styled.button<{ $active: boolean }>`border: 1px solid ${({ $active, theme }) => ($active ? theme.colors.brand.primary : theme.colors.border.default)}; border-radius: 999px; padding: 8px 12px; background: ${({ $active, theme }) => ($active ? theme.colors.brand.primary : theme.colors.background.default)}; color: ${({ $active, theme }) => ($active ? theme.colors.text.inverse : theme.colors.text.muted)}; cursor: pointer; font-size: 12px;`
export const VoteCard = styled.section`border-radius: 28px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle};`
export const Notice = styled.p`margin: 0 0 16px; border-radius: 12px; padding: 12px; background: ${({ theme }) => theme.colors.background.muted}; color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px;`
export const VoteRow = styled.div`display: flex; align-items: center; justify-content: space-between; gap: 16px; border-bottom: 1px solid ${({ theme }) => theme.colors.border.subtle}; padding: 16px 0; div { display: flex; flex-direction: column; gap: 4px; } small { color: ${({ theme }) => theme.colors.text.muted}; font-size: 11px; } strong { color: ${({ theme }) => theme.colors.text.strong}; font-size: 15px; }`
export const CheckButton = styled.button<{ $selected: boolean }>`min-width: 72px; min-height: 36px; border: 1px solid ${({ $selected, theme }) => ($selected ? theme.colors.brand.primary : theme.colors.brand.strong)}; border-radius: 999px; background: ${({ $selected, theme }) => ($selected ? theme.colors.brand.primary : theme.colors.background.default)}; color: ${({ $selected, theme }) => ($selected ? 'var(--pt-bg-default)' : theme.colors.brand.strong)}; cursor: pointer; font-size: 12px; font-weight: 600;`
export const SelectedList = styled.ul`display: grid; width: 100%; gap: 8px; margin: 0; padding: 0; color: ${({ theme }) => theme.colors.text.strong}; list-style: none;`
export const CartItem = styled.li`display: flex; align-items: center; justify-content: space-between; gap: 12px; border: 1px solid ${({ theme }) => theme.colors.border.subtle}; border-radius: 12px; padding: 10px 12px; background: ${({ theme }) => theme.colors.background.subtle}; button { border: 0; border-radius: 999px; padding: 6px 10px; background: transparent; color: ${({ theme }) => theme.colors.brand.strong}; cursor: pointer; font-size: 11px; }`
export const CartChoiceButton = styled.button<{ $selected: boolean }>`background: ${({ $selected, theme }) => ($selected ? theme.colors.brand.primary : theme.colors.background.default)} !important; color: ${({ $selected, theme }) => ($selected ? theme.colors.text.inverse : theme.colors.brand.strong)} !important;`
export const ProgressLayout = styled.div`display: grid; gap: 24px; grid-template-columns: minmax(0, 1fr) 360px; @media (max-width: 800px) { grid-template-columns: 1fr; }`
export const SideSummary = styled.aside`border-radius: 28px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; h2 { margin: 0 0 12px; color: ${({ theme }) => theme.colors.text.strong}; font-size: 18px; } p { color: ${({ theme }) => theme.colors.text.muted}; font-size: 14px; line-height: 1.6; } button { border: 0; padding: 0; background: transparent; color: ${({ theme }) => theme.colors.brand.primary}; cursor: pointer; font-weight: 600; }`
export const ProgressTrack = styled.div`width: 100%; height: 8px; overflow: hidden; border-radius: 4px; background: var(--pt-border-subtle);`
export const ProgressBar = styled.span<{ $progress: number }>`display: block; width: ${({ $progress }) => `${$progress}%`}; height: 100%; border-radius: inherit; background: ${({ theme }) => theme.colors.brand.primary};`
export const StatusPill = styled.span<{ $warning?: boolean }>`border-radius: 999px; padding: 8px 12px; background: ${({ $warning }) => ($warning ? 'var(--pt-bg-warning)' : 'var(--pt-bg-info)')}; color: ${({ $warning, theme }) => ($warning ? 'var(--pt-status-warning)' : theme.colors.brand.strong)}; font-size: 12px;`
export const PlaceLayout = styled.div`display: grid; gap: 24px; grid-template-columns: minmax(0, 1fr) 476px; @media (max-width: 900px) { grid-template-columns: 1fr; }`
export const PlaceImage = styled.img`display: block; width: 100%; height: 480px; border-radius: 28px; object-fit: cover; @media (max-width: 560px) { height: 320px; }`
export const Badge = styled.span`border-radius: 999px; padding: 4px 8px; background: var(--pt-bg-info); color: ${({ theme }) => theme.colors.brand.strong}; font-size: 12px;`
