import { lazy } from 'react'

export const ChangePasswordPage = lazy(() => import('@pages/change-password').then((module) => ({ default: module.ChangePasswordPage })))
export const CommunityPage = lazy(() => import('@pages/community').then((module) => ({ default: module.CommunityPage })))
export const DiagnosisPage = lazy(() => import('@pages/diagnosis').then((module) => ({ default: module.DiagnosisPage })))
export const DiagnosisResultPage = lazy(() => import('@pages/diagnosis-result').then((module) => ({ default: module.DiagnosisResultPage })))
export const LoginPage = lazy(() => import('@pages/login').then((module) => ({ default: module.LoginPage })))
export const MainPage = lazy(() => import('@pages/main').then((module) => ({ default: module.MainPage })))
export const MissionPage = lazy(() => import('@pages/mission').then((module) => ({ default: module.MissionPage })))
export const NotFoundPage = lazy(() => import('@pages/not-found').then((module) => ({ default: module.NotFoundPage })))
export const ProfilePage = lazy(() => import('@pages/profile').then((module) => ({ default: module.ProfilePage })))
export const RecordPage = lazy(() => import('@pages/record').then((module) => ({ default: module.RecordPage })))
export const ProfileEditPage = lazy(() => import('@pages/profile-edit').then((module) => ({ default: module.ProfileEditPage })))
export const SignUpPage = lazy(() => import('@pages/sign-up').then((module) => ({ default: module.SignUpPage })))
export const TravelSelectPage = lazy(() => import('@pages/travel-select').then((module) => ({ default: module.TravelSelectPage })))
