import { Suspense, type ReactNode } from 'react'
import { createBrowserRouter, Navigate } from 'react-router-dom'

import { paths } from './paths'
import { RequireAuth } from './RequireAuth'
import { RouteFallback } from './RouteFallback'
import {
  ChangePasswordPage,
  CommunityDetailPage,
  CommunityPage,
  CommunityWritePage,
  DiagnosisPage,
  DiagnosisResultPage,
  LoginPage,
  MainPage,
  MissionPage,
  NotFoundPage,
  NotificationDetailPage,
  NotificationPage,
  NotificationSettingsPage,
  PlannerCreatePage,
  PlannerDestinationPage,
  PlannerExplorePage,
  PlannerFinalPage,
  PlannerGroupPage,
  PlannerLineupPage,
  PlannerPage,
  PlannerPlacePage,
  PlannerProgressPage,
  PlannerVotePage,
  ProfileEditPage,
  ProfileAchievementsPage,
  ProfileCountriesPage,
  ProfileMapPage,
  ProfilePage,
  RecordPage,
  RecordMapPage,
  RecordCalendarPage,
  RecordCameraDetailPage,
  RecordCameraPage,
  RecordCameraWritePage,
  RecordDetailPage,
  RecordWritePage,
  SignUpPage,
  TravelSelectPage,
  TripCardCreatePage,
  TripCardDeletePage,
  TripCardDetailPage,
  TripCardsPage,
} from './lazyPages'

const withFallback = (element: ReactNode) => (
  <Suspense fallback={<RouteFallback />}>{element}</Suspense>
)

const requireAuth = (element: ReactNode) => withFallback(<RequireAuth>{element}</RequireAuth>)

export const router = createBrowserRouter([
  { path: '/', element: <Navigate to={paths.main} replace /> },
  { path: paths.signUp, element: withFallback(<SignUpPage />) },
  { path: paths.login, element: withFallback(<LoginPage />) },
  { path: paths.changePassword, element: withFallback(<ChangePasswordPage />) },
  { path: paths.diagnosis, element: requireAuth(<DiagnosisPage />) },
  { path: paths.diagnosisResult, element: requireAuth(<DiagnosisResultPage />) },
  { path: paths.main, element: requireAuth(<MainPage />) },
  { path: paths.planner, element: requireAuth(<PlannerPage />) },
  { path: paths.plannerCreate, element: requireAuth(<PlannerCreatePage />) },
  { path: paths.plannerGroup, element: requireAuth(<PlannerGroupPage />) },
  { path: paths.plannerDestination, element: requireAuth(<PlannerDestinationPage />) },
  { path: paths.plannerExplore, element: requireAuth(<PlannerExplorePage />) },
  { path: paths.plannerVote, element: requireAuth(<PlannerVotePage />) },
  { path: paths.plannerLineup, element: requireAuth(<PlannerLineupPage />) },
  { path: paths.plannerProgress, element: requireAuth(<PlannerProgressPage />) },
  { path: paths.plannerFinal, element: requireAuth(<PlannerFinalPage />) },
  { path: paths.plannerPlace, element: requireAuth(<PlannerPlacePage />) },
  { path: paths.profile, element: requireAuth(<ProfilePage />) },
  { path: paths.profileEdit, element: requireAuth(<ProfileEditPage />) },
  { path: paths.profileMap, element: requireAuth(<ProfileMapPage />) },
  { path: paths.profileCountries, element: requireAuth(<ProfileCountriesPage />) },
  { path: paths.profileAchievements, element: requireAuth(<ProfileAchievementsPage />) },
  { path: paths.travelSelect, element: requireAuth(<TravelSelectPage />) },
  { path: paths.community, element: requireAuth(<CommunityPage />) },
  { path: paths.communityWrite, element: requireAuth(<CommunityWritePage />) },
  { path: paths.communityDetail, element: requireAuth(<CommunityDetailPage />) },
  { path: paths.record, element: requireAuth(<RecordPage />) },
  { path: paths.recordMap, element: requireAuth(<RecordMapPage />) },
  { path: paths.recordCalendar, element: requireAuth(<RecordCalendarPage />) },
  { path: paths.recordCamera, element: requireAuth(<RecordCameraPage />) },
  { path: paths.recordCameraDetail, element: requireAuth(<RecordCameraDetailPage />) },
  { path: paths.recordCameraWrite, element: requireAuth(<RecordCameraWritePage />) },
  { path: paths.recordWrite, element: requireAuth(<RecordWritePage />) },
  { path: paths.recordDetail, element: requireAuth(<RecordDetailPage />) },
  { path: paths.mission, element: requireAuth(<MissionPage />) },
  { path: paths.tripCards, element: requireAuth(<TripCardsPage />) },
  { path: paths.tripCardDetail, element: requireAuth(<TripCardDetailPage />) },
  { path: paths.tripCardCreate, element: requireAuth(<TripCardCreatePage />) },
  { path: paths.tripCardDelete, element: requireAuth(<TripCardDeletePage />) },
  { path: paths.notifications, element: requireAuth(<NotificationPage />) },
  { path: paths.notificationDetail, element: requireAuth(<NotificationDetailPage />) },
  { path: paths.notificationSettings, element: requireAuth(<NotificationSettingsPage />) },
  { path: '*', element: withFallback(<NotFoundPage />) },
])
