import styled from 'styled-components'

export const Page = styled.div`width: min(100%, 1200px); margin: 0 auto;`
export const Header = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 24px; @media (max-width: 620px) { flex-direction: column; }`
export const Title = styled.h1`margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 32px; line-height: 40px;`
export const Subtitle = styled.p`margin: 6px 0 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 15px;`
export const ActionRow = styled.div`display: flex; flex-wrap: wrap; gap: 8px;`
export const Notice = styled.p`margin: 0 0 16px; border-radius: 12px; padding: 12px 16px; background: ${({ theme }) => theme.colors.background.muted}; color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; line-height: 1.6;`
export const State = styled.p`padding: 64px 0; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const CardGrid = styled.div`display: grid; gap: 24px; grid-template-columns: repeat(3, minmax(0, 1fr)); @media (max-width: 900px) { grid-template-columns: repeat(2, minmax(0, 1fr)); } @media (max-width: 560px) { grid-template-columns: 1fr; }`
export const Card = styled.button`overflow: hidden; border: 0; border-radius: 28px; padding: 0 0 20px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; text-align: left; img { display: block; width: 100%; height: 170px; object-fit: cover; } div { display: flex; flex-direction: column; gap: 6px; padding: 16px 20px 0; } strong { font-size: 18px; } span, small { color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
export const Empty = styled.p`margin: 0; padding: 64px; border-radius: 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const Detail = styled.section`overflow: hidden; border-radius: 28px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle};`
export const DetailHero = styled.div`display: grid; grid-template-columns: 1fr 1fr; align-items: stretch; img { display: block; width: 100%; height: 320px; object-fit: cover; } div { display: flex; flex-direction: column; align-items: flex-start; justify-content: center; gap: 12px; padding: 32px; } h2, p { margin: 0; } h2 { color: ${({ theme }) => theme.colors.text.strong}; font-size: 28px; } p { color: ${({ theme }) => theme.colors.text.muted}; } @media (max-width: 700px) { grid-template-columns: 1fr; img { height: 220px; } }`
export const Badge = styled.span`border-radius: 999px; padding: 4px 8px; background: var(--pt-bg-info); color: ${({ theme }) => theme.colors.brand.strong}; font-size: 12px;`
export const DetailBody = styled.div`display: flex; flex-direction: column; align-items: flex-start; gap: 12px; padding: 24px 32px 32px; border-top: 1px solid ${({ theme }) => theme.colors.border.subtle}; h3 { margin: 0 0 4px; color: ${({ theme }) => theme.colors.text.strong}; font-size: 18px; } p { margin: 0; color: ${({ theme }) => theme.colors.text.muted}; }`
export const SelectList = styled.section`display: flex; flex-direction: column; gap: 8px; border-radius: 28px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle};`
export const SelectRow = styled.div`display: flex; align-items: center; justify-content: space-between; gap: 16px; border-bottom: 1px solid ${({ theme }) => theme.colors.border.subtle}; padding: 16px 0; div, label { display: flex; align-items: center; gap: 12px; } label { color: ${({ theme }) => theme.colors.text.strong}; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; } strong { color: ${({ theme }) => theme.colors.text.strong}; } input { width: 18px; height: 18px; }`
