import styled from 'styled-components'

export const Page = styled.div`width: min(100%, 1200px); margin: 0 auto;`
export const Header = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 24px; @media (max-width: 560px) { flex-direction: column; }`
export const Title = styled.h1`margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 32px; line-height: 40px;`
export const Subtitle = styled.p`margin: 6px 0 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 15px;`
export const BackButton = styled.button`min-height: 46px; border: 1px solid ${({ theme }) => theme.colors.brand.strong}; border-radius: 12px; padding: 12px 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.brand.strong}; cursor: pointer; font-weight: 600;`
export const Body = styled.div`display: grid; gap: 24px; grid-template-columns: minmax(0, 1fr) 320px; @media (max-width: 800px) { grid-template-columns: 1fr; }`
export const Map = styled.div`position: relative; min-height: 560px; overflow: hidden; border-radius: 28px; background: #dbeaf2; box-shadow: ${({ theme }) => theme.shadows.subtle}; img { display: block; width: 100%; height: 100%; min-height: 560px; object-fit: cover; } @media (max-width: 560px) { min-height: 360px; img { min-height: 360px; } }`
export const Pin = styled.span<{ $index: number }>`position: absolute; top: ${({ $index }) => `${28 + ($index * 13) % 50}%`}; left: ${({ $index }) => `${18 + ($index * 19) % 66}%`}; width: 18px; height: 18px; border: 3px solid #fff; border-radius: 50%; background: ${({ theme }) => theme.colors.brand.primary}; box-shadow: 0 2px 10px rgb(16 42 66 / 20%);`
export const List = styled.aside`display: flex; flex-direction: column; gap: 8px; border-radius: 28px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; h2 { margin: 0 0 8px; color: ${({ theme }) => theme.colors.text.strong}; font-size: 18px; } p { color: ${({ theme }) => theme.colors.text.muted}; font-size: 14px; } button { display: flex; flex-direction: column; align-items: flex-start; gap: 4px; border: 0; border-bottom: 1px solid ${({ theme }) => theme.colors.border.subtle}; padding: 12px 0; background: transparent; color: ${({ theme }) => theme.colors.text.strong}; cursor: pointer; text-align: left; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
