export const paths = {
  kakaoCallback: '/auth/kakao/callback',
  login: '/login',
  main: '/main',
  planner: '/planner',
  plannerDestination: '/planner/destination',
  plannerExplore: '/planner/explore',
  plannerProgress: '/planner/progress',
  plannerInvite: '/planner/invite',
  profile: '/profile',
  profileEdit: '/profile/edit',
  profileTravelPreferences: '/profile/travel-preferences',
  profileGuardians: '/profile/guardians',
  profileAccessibility: '/profile/accessibility',
  profileMap: '/profile/map',
  profileCountries: '/profile/countries',
  profileAchievements: '/profile/achievements',
  notifications: '/notifications',
  notificationSettings: '/settings/notifications',
  tripCards: '/trip-cards',
  tripCardCreate: '/trip-cards/new',
  record: '/record',
  recordCalendar: '/record/calendar',
  recordWrite: '/record/write',
  signUp: '/sign-up',
} as const
