import styled from 'styled-components'

export const Page = styled.div`width: min(100%, 1200px); margin: 0 auto;`
export const Header = styled.header`display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; margin-bottom: 24px; @media (max-width: 560px) { flex-direction: column; }`
export const Title = styled.h1`margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 32px; line-height: 40px;`
export const Subtitle = styled.p`margin: 6px 0 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 15px;`
export const BackButton = styled.button`min-height: 46px; border: 1px solid ${({ theme }) => theme.colors.brand.strong}; border-radius: 12px; padding: 12px 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.brand.strong}; cursor: pointer; font-weight: 600;`
export const State = styled.p`padding: 64px 0; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const MapCard = styled.section`position: relative; min-height: 560px; overflow: hidden; border-radius: 28px; padding: 0; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; img { display: block; width: 100%; height: 560px; object-fit: contain; padding: 24px; } @media (max-width: 560px) { min-height: 360px; img { height: 360px; padding: 12px; } }`
export const MapLegend = styled.div`position: absolute; top: 24px; left: 24px; display: inline-flex; align-items: center; gap: 8px; border-radius: 999px; padding: 8px 12px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; box-shadow: ${({ theme }) => theme.shadows.subtle}; span { width: 10px; height: 10px; border-radius: 50%; background: ${({ theme }) => theme.colors.brand.primary}; }`
export const MapNote = styled.p`position: absolute; right: 24px; bottom: 24px; margin: 0; border-radius: 12px; padding: 12px 16px; background: rgb(255 255 255 / 92%); color: ${({ theme }) => theme.colors.text.strong}; font-size: 13px;`
export const MapSummary = styled.section`display: grid; gap: 16px; margin-top: 20px; grid-template-columns: repeat(3, minmax(0, 1fr)); div { display: flex; min-height: 108px; flex-direction: column; align-items: center; justify-content: center; gap: 8px; border-radius: 20px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; } strong { color: ${({ theme }) => theme.colors.brand.strong}; font-size: 30px; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; } @media (max-width: 560px) { grid-template-columns: 1fr; }`
export const MapCountrySection = styled.section`margin-top: 28px; h2 { margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 20px; } p { margin: 6px 0 16px; color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; }`
export const CountryGrid = styled.div`display: grid; gap: 16px; grid-template-columns: repeat(4, minmax(0, 1fr)); @media (max-width: 800px) { grid-template-columns: repeat(2, minmax(0, 1fr)); } @media (max-width: 420px) { grid-template-columns: 1fr; }`
export const CountryCard = styled.article<{ $selected?: boolean }>`min-height: 120px; display: flex; flex-direction: column; justify-content: flex-end; border: 0; border-radius: 20px; padding: 20px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; text-align: left; cursor: ${({ as }) => as === 'button' ? 'pointer' : 'default'}; outline: ${({ $selected, theme }) => $selected ? `3px solid ${theme.colors.brand.primary}` : 'none'}; strong { color: ${({ theme }) => theme.colors.text.strong}; font-size: 18px; } span { margin-top: 6px; color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; }`
export const CountryDetail = styled.section`margin-top: 28px; border-radius: 20px; padding: 24px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; h2 { margin: 0; color: ${({ theme }) => theme.colors.text.strong}; font-size: 20px; } p { margin: 6px 0 16px; color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; }`
export const CountryTripList = styled.div`display: grid; gap: 10px;`
export const CountryTripButton = styled.button`display: flex; align-items: center; justify-content: space-between; gap: 16px; border: 1px solid ${({ theme }) => theme.colors.border.default}; border-radius: 12px; padding: 14px 16px; background: ${({ theme }) => theme.colors.background.default}; text-align: left; cursor: pointer; strong { color: ${({ theme }) => theme.colors.text.strong}; } span { margin: 0; color: ${({ theme }) => theme.colors.text.muted}; font-size: 12px; } @media (max-width: 560px) { align-items: flex-start; flex-direction: column; gap: 6px; }`
export const CountryBadge = styled.span`align-self: flex-start; margin: 0 0 auto !important; border-radius: 999px; padding: 5px 8px; background: ${({ theme }) => theme.colors.brand.primary}; color: ${({ theme }) => theme.colors.background.default} !important; font-size: 11px !important; font-weight: 700;`
export const Empty = styled.p`grid-column: 1 / -1; margin: 0; padding: 64px; border-radius: 20px; background: ${({ theme }) => theme.colors.background.default}; color: ${({ theme }) => theme.colors.text.muted}; text-align: center;`
export const AchievementGrid = styled.div`display: grid; gap: 24px; grid-template-columns: repeat(4, minmax(0, 1fr)); @media (max-width: 760px) { grid-template-columns: repeat(2, minmax(0, 1fr)); }`
export const Achievement = styled.article`display: flex; min-height: 180px; flex-direction: column; align-items: center; justify-content: center; gap: 8px; border-radius: 28px; background: ${({ theme }) => theme.colors.background.default}; box-shadow: ${({ theme }) => theme.shadows.subtle}; strong { color: ${({ theme }) => theme.colors.brand.strong}; font-size: 40px; } span { color: ${({ theme }) => theme.colors.text.muted}; font-size: 13px; }`
