/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appAuthenticatedRouteRouteImport } from './routes/(app)/_authenticated/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as publicLoginIndexRouteImport } from './routes/(public)/login/index'
import { Route as publicPrivacyIndexRouteImport } from './routes/(public)/privacy/index'
import { Route as publicSignUpIndexRouteImport } from './routes/(public)/sign-up/index'
import { Route as appAuthenticatedMainIndexRouteImport } from './routes/(app)/_authenticated/main/index'
import { Route as appAuthenticatedNotificationsIndexRouteImport } from './routes/(app)/_authenticated/notifications/index'
import { Route as appAuthenticatedPlannerIndexRouteImport } from './routes/(app)/_authenticated/planner/index'
import { Route as appAuthenticatedProfileIndexRouteImport } from './routes/(app)/_authenticated/profile/index'
import { Route as appAuthenticatedRecordIndexRouteImport } from './routes/(app)/_authenticated/record/index'
import { Route as appAuthenticatedTripCardsIndexRouteImport } from './routes/(app)/_authenticated/trip-cards/index'
import { Route as appAuthenticatedNotificationsNotificationIdIndexRouteImport } from './routes/(app)/_authenticated/notifications/$notificationId/index'
import { Route as appAuthenticatedPlannerDestinationIndexRouteImport } from './routes/(app)/_authenticated/planner/destination/index'
import { Route as appAuthenticatedPlannerExploreIndexRouteImport } from './routes/(app)/_authenticated/planner/explore/index'
import { Route as appAuthenticatedPlannerGroupIndexRouteImport } from './routes/(app)/_authenticated/planner/group/index'
import { Route as appAuthenticatedPlannerInviteIndexRouteImport } from './routes/(app)/_authenticated/planner/invite/index'
import { Route as appAuthenticatedPlannerProgressIndexRouteImport } from './routes/(app)/_authenticated/planner/progress/index'
import { Route as appAuthenticatedProfileAccessibilityIndexRouteImport } from './routes/(app)/_authenticated/profile/accessibility/index'
import { Route as appAuthenticatedProfileAchievementsIndexRouteImport } from './routes/(app)/_authenticated/profile/achievements/index'
import { Route as appAuthenticatedProfileClaimIndexRouteImport } from './routes/(app)/_authenticated/profile/claim/index'
import { Route as appAuthenticatedProfileCountriesIndexRouteImport } from './routes/(app)/_authenticated/profile/countries/index'
import { Route as appAuthenticatedProfileEditIndexRouteImport } from './routes/(app)/_authenticated/profile/edit/index'
import { Route as appAuthenticatedProfileGuardiansIndexRouteImport } from './routes/(app)/_authenticated/profile/guardians/index'
import { Route as appAuthenticatedProfileMapIndexRouteImport } from './routes/(app)/_authenticated/profile/map/index'
import { Route as appAuthenticatedProfileTravelPreferencesIndexRouteImport } from './routes/(app)/_authenticated/profile/travel-preferences/index'
import { Route as appAuthenticatedRecordRecordIdIndexRouteImport } from './routes/(app)/_authenticated/record/$recordId/index'
import { Route as appAuthenticatedRecordCalendarIndexRouteImport } from './routes/(app)/_authenticated/record/calendar/index'
import { Route as appAuthenticatedRecordDeleteIndexRouteImport } from './routes/(app)/_authenticated/record/delete/index'
import { Route as appAuthenticatedRecordMapIndexRouteImport } from './routes/(app)/_authenticated/record/map/index'
import { Route as appAuthenticatedRecordReportIndexRouteImport } from './routes/(app)/_authenticated/record/report/index'
import { Route as appAuthenticatedRecordWriteIndexRouteImport } from './routes/(app)/_authenticated/record/write/index'
import { Route as appAuthenticatedSettingsNotificationsIndexRouteImport } from './routes/(app)/_authenticated/settings/notifications/index'
import { Route as appAuthenticatedTravelSelectIndexRouteImport } from './routes/(app)/_authenticated/travel/select/index'
import { Route as appAuthenticatedTripCardsTripIdIndexRouteImport } from './routes/(app)/_authenticated/trip-cards/$tripId/index'
import { Route as appAuthenticatedTripCardsDeleteIndexRouteImport } from './routes/(app)/_authenticated/trip-cards/delete/index'
import { Route as appAuthenticatedTripCardsNewIndexRouteImport } from './routes/(app)/_authenticated/trip-cards/new/index'
import { Route as publicAuthKakaoCallbackIndexRouteImport } from './routes/(public)/auth/kakao/callback/index'
import { Route as appAuthenticatedRecordRecordIdEditIndexRouteImport } from './routes/(app)/_authenticated/record/$recordId/edit/index'

const appAuthenticatedRouteRoute = appAuthenticatedRouteRouteImport.update({
  id: '/(app)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginIndexRoute = publicLoginIndexRouteImport.update({
  id: '/(public)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyIndexRoute = publicPrivacyIndexRouteImport.update({
  id: '/(public)/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpIndexRoute = publicSignUpIndexRouteImport.update({
  id: '/(public)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthenticatedMainIndexRoute =
  appAuthenticatedMainIndexRouteImport.update({
    id: '/main/',
    path: '/main/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedNotificationsIndexRoute =
  appAuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerIndexRoute =
  appAuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileIndexRoute =
  appAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordIndexRoute =
  appAuthenticatedRecordIndexRouteImport.update({
    id: '/record/',
    path: '/record/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedTripCardsIndexRoute =
  appAuthenticatedTripCardsIndexRouteImport.update({
    id: '/trip-cards/',
    path: '/trip-cards/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedNotificationsNotificationIdIndexRoute =
  appAuthenticatedNotificationsNotificationIdIndexRouteImport.update({
    id: '/notifications/$notificationId/',
    path: '/notifications/$notificationId/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerDestinationIndexRoute =
  appAuthenticatedPlannerDestinationIndexRouteImport.update({
    id: '/planner/destination/',
    path: '/planner/destination/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerExploreIndexRoute =
  appAuthenticatedPlannerExploreIndexRouteImport.update({
    id: '/planner/explore/',
    path: '/planner/explore/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerGroupIndexRoute =
  appAuthenticatedPlannerGroupIndexRouteImport.update({
    id: '/planner/group/',
    path: '/planner/group/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerInviteIndexRoute =
  appAuthenticatedPlannerInviteIndexRouteImport.update({
    id: '/planner/invite/',
    path: '/planner/invite/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedPlannerProgressIndexRoute =
  appAuthenticatedPlannerProgressIndexRouteImport.update({
    id: '/planner/progress/',
    path: '/planner/progress/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileAccessibilityIndexRoute =
  appAuthenticatedProfileAccessibilityIndexRouteImport.update({
    id: '/profile/accessibility/',
    path: '/profile/accessibility/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileAchievementsIndexRoute =
  appAuthenticatedProfileAchievementsIndexRouteImport.update({
    id: '/profile/achievements/',
    path: '/profile/achievements/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileClaimIndexRoute =
  appAuthenticatedProfileClaimIndexRouteImport.update({
    id: '/profile/claim/',
    path: '/profile/claim/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileCountriesIndexRoute =
  appAuthenticatedProfileCountriesIndexRouteImport.update({
    id: '/profile/countries/',
    path: '/profile/countries/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileEditIndexRoute =
  appAuthenticatedProfileEditIndexRouteImport.update({
    id: '/profile/edit/',
    path: '/profile/edit/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileGuardiansIndexRoute =
  appAuthenticatedProfileGuardiansIndexRouteImport.update({
    id: '/profile/guardians/',
    path: '/profile/guardians/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileMapIndexRoute =
  appAuthenticatedProfileMapIndexRouteImport.update({
    id: '/profile/map/',
    path: '/profile/map/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedProfileTravelPreferencesIndexRoute =
  appAuthenticatedProfileTravelPreferencesIndexRouteImport.update({
    id: '/profile/travel-preferences/',
    path: '/profile/travel-preferences/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordRecordIdIndexRoute =
  appAuthenticatedRecordRecordIdIndexRouteImport.update({
    id: '/record/$recordId/',
    path: '/record/$recordId/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordCalendarIndexRoute =
  appAuthenticatedRecordCalendarIndexRouteImport.update({
    id: '/record/calendar/',
    path: '/record/calendar/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordDeleteIndexRoute =
  appAuthenticatedRecordDeleteIndexRouteImport.update({
    id: '/record/delete/',
    path: '/record/delete/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordMapIndexRoute =
  appAuthenticatedRecordMapIndexRouteImport.update({
    id: '/record/map/',
    path: '/record/map/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordReportIndexRoute =
  appAuthenticatedRecordReportIndexRouteImport.update({
    id: '/record/report/',
    path: '/record/report/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedRecordWriteIndexRoute =
  appAuthenticatedRecordWriteIndexRouteImport.update({
    id: '/record/write/',
    path: '/record/write/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedSettingsNotificationsIndexRoute =
  appAuthenticatedSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedTravelSelectIndexRoute =
  appAuthenticatedTravelSelectIndexRouteImport.update({
    id: '/travel/select/',
    path: '/travel/select/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedTripCardsTripIdIndexRoute =
  appAuthenticatedTripCardsTripIdIndexRouteImport.update({
    id: '/trip-cards/$tripId/',
    path: '/trip-cards/$tripId/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedTripCardsDeleteIndexRoute =
  appAuthenticatedTripCardsDeleteIndexRouteImport.update({
    id: '/trip-cards/delete/',
    path: '/trip-cards/delete/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const appAuthenticatedTripCardsNewIndexRoute =
  appAuthenticatedTripCardsNewIndexRouteImport.update({
    id: '/trip-cards/new/',
    path: '/trip-cards/new/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)
const publicAuthKakaoCallbackIndexRoute =
  publicAuthKakaoCallbackIndexRouteImport.update({
    id: '/(public)/auth/kakao/callback/',
    path: '/auth/kakao/callback/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appAuthenticatedRecordRecordIdEditIndexRoute =
  appAuthenticatedRecordRecordIdEditIndexRouteImport.update({
    id: '/record/$recordId/edit/',
    path: '/record/$recordId/edit/',
    getParentRoute: () => appAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/login/': typeof publicLoginIndexRoute
  '/privacy/': typeof publicPrivacyIndexRoute
  '/sign-up/': typeof publicSignUpIndexRoute
  '/main/': typeof appAuthenticatedMainIndexRoute
  '/notifications/': typeof appAuthenticatedNotificationsIndexRoute
  '/planner/': typeof appAuthenticatedPlannerIndexRoute
  '/profile/': typeof appAuthenticatedProfileIndexRoute
  '/record/': typeof appAuthenticatedRecordIndexRoute
  '/trip-cards/': typeof appAuthenticatedTripCardsIndexRoute
  '/notifications/$notificationId/': typeof appAuthenticatedNotificationsNotificationIdIndexRoute
  '/planner/destination/': typeof appAuthenticatedPlannerDestinationIndexRoute
  '/planner/explore/': typeof appAuthenticatedPlannerExploreIndexRoute
  '/planner/group/': typeof appAuthenticatedPlannerGroupIndexRoute
  '/planner/invite/': typeof appAuthenticatedPlannerInviteIndexRoute
  '/planner/progress/': typeof appAuthenticatedPlannerProgressIndexRoute
  '/profile/accessibility/': typeof appAuthenticatedProfileAccessibilityIndexRoute
  '/profile/achievements/': typeof appAuthenticatedProfileAchievementsIndexRoute
  '/profile/claim/': typeof appAuthenticatedProfileClaimIndexRoute
  '/profile/countries/': typeof appAuthenticatedProfileCountriesIndexRoute
  '/profile/edit/': typeof appAuthenticatedProfileEditIndexRoute
  '/profile/guardians/': typeof appAuthenticatedProfileGuardiansIndexRoute
  '/profile/map/': typeof appAuthenticatedProfileMapIndexRoute
  '/profile/travel-preferences/': typeof appAuthenticatedProfileTravelPreferencesIndexRoute
  '/record/$recordId/': typeof appAuthenticatedRecordRecordIdIndexRoute
  '/record/calendar/': typeof appAuthenticatedRecordCalendarIndexRoute
  '/record/delete/': typeof appAuthenticatedRecordDeleteIndexRoute
  '/record/map/': typeof appAuthenticatedRecordMapIndexRoute
  '/record/report/': typeof appAuthenticatedRecordReportIndexRoute
  '/record/write/': typeof appAuthenticatedRecordWriteIndexRoute
  '/settings/notifications/': typeof appAuthenticatedSettingsNotificationsIndexRoute
  '/travel/select/': typeof appAuthenticatedTravelSelectIndexRoute
  '/trip-cards/$tripId/': typeof appAuthenticatedTripCardsTripIdIndexRoute
  '/trip-cards/delete/': typeof appAuthenticatedTripCardsDeleteIndexRoute
  '/trip-cards/new/': typeof appAuthenticatedTripCardsNewIndexRoute
  '/auth/kakao/callback/': typeof publicAuthKakaoCallbackIndexRoute
  '/record/$recordId/edit/': typeof appAuthenticatedRecordRecordIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/login': typeof publicLoginIndexRoute
  '/privacy': typeof publicPrivacyIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
  '/main': typeof appAuthenticatedMainIndexRoute
  '/notifications': typeof appAuthenticatedNotificationsIndexRoute
  '/planner': typeof appAuthenticatedPlannerIndexRoute
  '/profile': typeof appAuthenticatedProfileIndexRoute
  '/record': typeof appAuthenticatedRecordIndexRoute
  '/trip-cards': typeof appAuthenticatedTripCardsIndexRoute
  '/notifications/$notificationId': typeof appAuthenticatedNotificationsNotificationIdIndexRoute
  '/planner/destination': typeof appAuthenticatedPlannerDestinationIndexRoute
  '/planner/explore': typeof appAuthenticatedPlannerExploreIndexRoute
  '/planner/group': typeof appAuthenticatedPlannerGroupIndexRoute
  '/planner/invite': typeof appAuthenticatedPlannerInviteIndexRoute
  '/planner/progress': typeof appAuthenticatedPlannerProgressIndexRoute
  '/profile/accessibility': typeof appAuthenticatedProfileAccessibilityIndexRoute
  '/profile/achievements': typeof appAuthenticatedProfileAchievementsIndexRoute
  '/profile/claim': typeof appAuthenticatedProfileClaimIndexRoute
  '/profile/countries': typeof appAuthenticatedProfileCountriesIndexRoute
  '/profile/edit': typeof appAuthenticatedProfileEditIndexRoute
  '/profile/guardians': typeof appAuthenticatedProfileGuardiansIndexRoute
  '/profile/map': typeof appAuthenticatedProfileMapIndexRoute
  '/profile/travel-preferences': typeof appAuthenticatedProfileTravelPreferencesIndexRoute
  '/record/$recordId': typeof appAuthenticatedRecordRecordIdIndexRoute
  '/record/calendar': typeof appAuthenticatedRecordCalendarIndexRoute
  '/record/delete': typeof appAuthenticatedRecordDeleteIndexRoute
  '/record/map': typeof appAuthenticatedRecordMapIndexRoute
  '/record/report': typeof appAuthenticatedRecordReportIndexRoute
  '/record/write': typeof appAuthenticatedRecordWriteIndexRoute
  '/settings/notifications': typeof appAuthenticatedSettingsNotificationsIndexRoute
  '/travel/select': typeof appAuthenticatedTravelSelectIndexRoute
  '/trip-cards/$tripId': typeof appAuthenticatedTripCardsTripIdIndexRoute
  '/trip-cards/delete': typeof appAuthenticatedTripCardsDeleteIndexRoute
  '/trip-cards/new': typeof appAuthenticatedTripCardsNewIndexRoute
  '/auth/kakao/callback': typeof publicAuthKakaoCallbackIndexRoute
  '/record/$recordId/edit': typeof appAuthenticatedRecordRecordIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_authenticated': typeof appAuthenticatedRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(public)/login/': typeof publicLoginIndexRoute
  '/(public)/privacy/': typeof publicPrivacyIndexRoute
  '/(public)/sign-up/': typeof publicSignUpIndexRoute
  '/(app)/_authenticated/main/': typeof appAuthenticatedMainIndexRoute
  '/(app)/_authenticated/notifications/': typeof appAuthenticatedNotificationsIndexRoute
  '/(app)/_authenticated/planner/': typeof appAuthenticatedPlannerIndexRoute
  '/(app)/_authenticated/profile/': typeof appAuthenticatedProfileIndexRoute
  '/(app)/_authenticated/record/': typeof appAuthenticatedRecordIndexRoute
  '/(app)/_authenticated/trip-cards/': typeof appAuthenticatedTripCardsIndexRoute
  '/(app)/_authenticated/notifications/$notificationId/': typeof appAuthenticatedNotificationsNotificationIdIndexRoute
  '/(app)/_authenticated/planner/destination/': typeof appAuthenticatedPlannerDestinationIndexRoute
  '/(app)/_authenticated/planner/explore/': typeof appAuthenticatedPlannerExploreIndexRoute
  '/(app)/_authenticated/planner/group/': typeof appAuthenticatedPlannerGroupIndexRoute
  '/(app)/_authenticated/planner/invite/': typeof appAuthenticatedPlannerInviteIndexRoute
  '/(app)/_authenticated/planner/progress/': typeof appAuthenticatedPlannerProgressIndexRoute
  '/(app)/_authenticated/profile/accessibility/': typeof appAuthenticatedProfileAccessibilityIndexRoute
  '/(app)/_authenticated/profile/achievements/': typeof appAuthenticatedProfileAchievementsIndexRoute
  '/(app)/_authenticated/profile/claim/': typeof appAuthenticatedProfileClaimIndexRoute
  '/(app)/_authenticated/profile/countries/': typeof appAuthenticatedProfileCountriesIndexRoute
  '/(app)/_authenticated/profile/edit/': typeof appAuthenticatedProfileEditIndexRoute
  '/(app)/_authenticated/profile/guardians/': typeof appAuthenticatedProfileGuardiansIndexRoute
  '/(app)/_authenticated/profile/map/': typeof appAuthenticatedProfileMapIndexRoute
  '/(app)/_authenticated/profile/travel-preferences/': typeof appAuthenticatedProfileTravelPreferencesIndexRoute
  '/(app)/_authenticated/record/$recordId/': typeof appAuthenticatedRecordRecordIdIndexRoute
  '/(app)/_authenticated/record/calendar/': typeof appAuthenticatedRecordCalendarIndexRoute
  '/(app)/_authenticated/record/delete/': typeof appAuthenticatedRecordDeleteIndexRoute
  '/(app)/_authenticated/record/map/': typeof appAuthenticatedRecordMapIndexRoute
  '/(app)/_authenticated/record/report/': typeof appAuthenticatedRecordReportIndexRoute
  '/(app)/_authenticated/record/write/': typeof appAuthenticatedRecordWriteIndexRoute
  '/(app)/_authenticated/settings/notifications/': typeof appAuthenticatedSettingsNotificationsIndexRoute
  '/(app)/_authenticated/travel/select/': typeof appAuthenticatedTravelSelectIndexRoute
  '/(app)/_authenticated/trip-cards/$tripId/': typeof appAuthenticatedTripCardsTripIdIndexRoute
  '/(app)/_authenticated/trip-cards/delete/': typeof appAuthenticatedTripCardsDeleteIndexRoute
  '/(app)/_authenticated/trip-cards/new/': typeof appAuthenticatedTripCardsNewIndexRoute
  '/(public)/auth/kakao/callback/': typeof publicAuthKakaoCallbackIndexRoute
  '/(app)/_authenticated/record/$recordId/edit/': typeof appAuthenticatedRecordRecordIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/privacy/'
    | '/sign-up/'
    | '/main/'
    | '/notifications/'
    | '/planner/'
    | '/profile/'
    | '/record/'
    | '/trip-cards/'
    | '/notifications/$notificationId/'
    | '/planner/destination/'
    | '/planner/explore/'
    | '/planner/group/'
    | '/planner/invite/'
    | '/planner/progress/'
    | '/profile/accessibility/'
    | '/profile/achievements/'
    | '/profile/claim/'
    | '/profile/countries/'
    | '/profile/edit/'
    | '/profile/guardians/'
    | '/profile/map/'
    | '/profile/travel-preferences/'
    | '/record/$recordId/'
    | '/record/calendar/'
    | '/record/delete/'
    | '/record/map/'
    | '/record/report/'
    | '/record/write/'
    | '/settings/notifications/'
    | '/travel/select/'
    | '/trip-cards/$tripId/'
    | '/trip-cards/delete/'
    | '/trip-cards/new/'
    | '/auth/kakao/callback/'
    | '/record/$recordId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/sign-up'
    | '/main'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/record'
    | '/trip-cards'
    | '/notifications/$notificationId'
    | '/planner/destination'
    | '/planner/explore'
    | '/planner/group'
    | '/planner/invite'
    | '/planner/progress'
    | '/profile/accessibility'
    | '/profile/achievements'
    | '/profile/claim'
    | '/profile/countries'
    | '/profile/edit'
    | '/profile/guardians'
    | '/profile/map'
    | '/profile/travel-preferences'
    | '/record/$recordId'
    | '/record/calendar'
    | '/record/delete'
    | '/record/map'
    | '/record/report'
    | '/record/write'
    | '/settings/notifications'
    | '/travel/select'
    | '/trip-cards/$tripId'
    | '/trip-cards/delete'
    | '/trip-cards/new'
    | '/auth/kakao/callback'
    | '/record/$recordId/edit'
  id:
    | '__root__'
    | '/(app)/_authenticated'
    | '/(home)/'
    | '/(public)/login/'
    | '/(public)/privacy/'
    | '/(public)/sign-up/'
    | '/(app)/_authenticated/main/'
    | '/(app)/_authenticated/notifications/'
    | '/(app)/_authenticated/planner/'
    | '/(app)/_authenticated/profile/'
    | '/(app)/_authenticated/record/'
    | '/(app)/_authenticated/trip-cards/'
    | '/(app)/_authenticated/notifications/$notificationId/'
    | '/(app)/_authenticated/planner/destination/'
    | '/(app)/_authenticated/planner/explore/'
    | '/(app)/_authenticated/planner/group/'
    | '/(app)/_authenticated/planner/invite/'
    | '/(app)/_authenticated/planner/progress/'
    | '/(app)/_authenticated/profile/accessibility/'
    | '/(app)/_authenticated/profile/achievements/'
    | '/(app)/_authenticated/profile/claim/'
    | '/(app)/_authenticated/profile/countries/'
    | '/(app)/_authenticated/profile/edit/'
    | '/(app)/_authenticated/profile/guardians/'
    | '/(app)/_authenticated/profile/map/'
    | '/(app)/_authenticated/profile/travel-preferences/'
    | '/(app)/_authenticated/record/$recordId/'
    | '/(app)/_authenticated/record/calendar/'
    | '/(app)/_authenticated/record/delete/'
    | '/(app)/_authenticated/record/map/'
    | '/(app)/_authenticated/record/report/'
    | '/(app)/_authenticated/record/write/'
    | '/(app)/_authenticated/settings/notifications/'
    | '/(app)/_authenticated/travel/select/'
    | '/(app)/_authenticated/trip-cards/$tripId/'
    | '/(app)/_authenticated/trip-cards/delete/'
    | '/(app)/_authenticated/trip-cards/new/'
    | '/(public)/auth/kakao/callback/'
    | '/(app)/_authenticated/record/$recordId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAuthenticatedRouteRoute: typeof appAuthenticatedRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
  publicLoginIndexRoute: typeof publicLoginIndexRoute
  publicPrivacyIndexRoute: typeof publicPrivacyIndexRoute
  publicSignUpIndexRoute: typeof publicSignUpIndexRoute
  publicAuthKakaoCallbackIndexRoute: typeof publicAuthKakaoCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_authenticated': {
      id: '/(app)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login/': {
      id: '/(public)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy/': {
      id: '/(public)/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof publicPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up/': {
      id: '/(public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof publicSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authenticated/main/': {
      id: '/(app)/_authenticated/main/'
      path: '/main'
      fullPath: '/main/'
      preLoaderRoute: typeof appAuthenticatedMainIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/notifications/': {
      id: '/(app)/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof appAuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/': {
      id: '/(app)/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof appAuthenticatedPlannerIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/': {
      id: '/(app)/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof appAuthenticatedProfileIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/': {
      id: '/(app)/_authenticated/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof appAuthenticatedRecordIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/trip-cards/': {
      id: '/(app)/_authenticated/trip-cards/'
      path: '/trip-cards'
      fullPath: '/trip-cards/'
      preLoaderRoute: typeof appAuthenticatedTripCardsIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/notifications/$notificationId/': {
      id: '/(app)/_authenticated/notifications/$notificationId/'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId/'
      preLoaderRoute: typeof appAuthenticatedNotificationsNotificationIdIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/destination/': {
      id: '/(app)/_authenticated/planner/destination/'
      path: '/planner/destination'
      fullPath: '/planner/destination/'
      preLoaderRoute: typeof appAuthenticatedPlannerDestinationIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/explore/': {
      id: '/(app)/_authenticated/planner/explore/'
      path: '/planner/explore'
      fullPath: '/planner/explore/'
      preLoaderRoute: typeof appAuthenticatedPlannerExploreIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/group/': {
      id: '/(app)/_authenticated/planner/group/'
      path: '/planner/group'
      fullPath: '/planner/group/'
      preLoaderRoute: typeof appAuthenticatedPlannerGroupIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/invite/': {
      id: '/(app)/_authenticated/planner/invite/'
      path: '/planner/invite'
      fullPath: '/planner/invite/'
      preLoaderRoute: typeof appAuthenticatedPlannerInviteIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/planner/progress/': {
      id: '/(app)/_authenticated/planner/progress/'
      path: '/planner/progress'
      fullPath: '/planner/progress/'
      preLoaderRoute: typeof appAuthenticatedPlannerProgressIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/accessibility/': {
      id: '/(app)/_authenticated/profile/accessibility/'
      path: '/profile/accessibility'
      fullPath: '/profile/accessibility/'
      preLoaderRoute: typeof appAuthenticatedProfileAccessibilityIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/achievements/': {
      id: '/(app)/_authenticated/profile/achievements/'
      path: '/profile/achievements'
      fullPath: '/profile/achievements/'
      preLoaderRoute: typeof appAuthenticatedProfileAchievementsIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/claim/': {
      id: '/(app)/_authenticated/profile/claim/'
      path: '/profile/claim'
      fullPath: '/profile/claim/'
      preLoaderRoute: typeof appAuthenticatedProfileClaimIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/countries/': {
      id: '/(app)/_authenticated/profile/countries/'
      path: '/profile/countries'
      fullPath: '/profile/countries/'
      preLoaderRoute: typeof appAuthenticatedProfileCountriesIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/edit/': {
      id: '/(app)/_authenticated/profile/edit/'
      path: '/profile/edit'
      fullPath: '/profile/edit/'
      preLoaderRoute: typeof appAuthenticatedProfileEditIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/guardians/': {
      id: '/(app)/_authenticated/profile/guardians/'
      path: '/profile/guardians'
      fullPath: '/profile/guardians/'
      preLoaderRoute: typeof appAuthenticatedProfileGuardiansIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/map/': {
      id: '/(app)/_authenticated/profile/map/'
      path: '/profile/map'
      fullPath: '/profile/map/'
      preLoaderRoute: typeof appAuthenticatedProfileMapIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/profile/travel-preferences/': {
      id: '/(app)/_authenticated/profile/travel-preferences/'
      path: '/profile/travel-preferences'
      fullPath: '/profile/travel-preferences/'
      preLoaderRoute: typeof appAuthenticatedProfileTravelPreferencesIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/$recordId/': {
      id: '/(app)/_authenticated/record/$recordId/'
      path: '/record/$recordId'
      fullPath: '/record/$recordId/'
      preLoaderRoute: typeof appAuthenticatedRecordRecordIdIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/calendar/': {
      id: '/(app)/_authenticated/record/calendar/'
      path: '/record/calendar'
      fullPath: '/record/calendar/'
      preLoaderRoute: typeof appAuthenticatedRecordCalendarIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/delete/': {
      id: '/(app)/_authenticated/record/delete/'
      path: '/record/delete'
      fullPath: '/record/delete/'
      preLoaderRoute: typeof appAuthenticatedRecordDeleteIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/map/': {
      id: '/(app)/_authenticated/record/map/'
      path: '/record/map'
      fullPath: '/record/map/'
      preLoaderRoute: typeof appAuthenticatedRecordMapIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/report/': {
      id: '/(app)/_authenticated/record/report/'
      path: '/record/report'
      fullPath: '/record/report/'
      preLoaderRoute: typeof appAuthenticatedRecordReportIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/record/write/': {
      id: '/(app)/_authenticated/record/write/'
      path: '/record/write'
      fullPath: '/record/write/'
      preLoaderRoute: typeof appAuthenticatedRecordWriteIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/settings/notifications/': {
      id: '/(app)/_authenticated/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof appAuthenticatedSettingsNotificationsIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/travel/select/': {
      id: '/(app)/_authenticated/travel/select/'
      path: '/travel/select'
      fullPath: '/travel/select/'
      preLoaderRoute: typeof appAuthenticatedTravelSelectIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/trip-cards/$tripId/': {
      id: '/(app)/_authenticated/trip-cards/$tripId/'
      path: '/trip-cards/$tripId'
      fullPath: '/trip-cards/$tripId/'
      preLoaderRoute: typeof appAuthenticatedTripCardsTripIdIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/trip-cards/delete/': {
      id: '/(app)/_authenticated/trip-cards/delete/'
      path: '/trip-cards/delete'
      fullPath: '/trip-cards/delete/'
      preLoaderRoute: typeof appAuthenticatedTripCardsDeleteIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(app)/_authenticated/trip-cards/new/': {
      id: '/(app)/_authenticated/trip-cards/new/'
      path: '/trip-cards/new'
      fullPath: '/trip-cards/new/'
      preLoaderRoute: typeof appAuthenticatedTripCardsNewIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
    '/(public)/auth/kakao/callback/': {
      id: '/(public)/auth/kakao/callback/'
      path: '/auth/kakao/callback'
      fullPath: '/auth/kakao/callback/'
      preLoaderRoute: typeof publicAuthKakaoCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authenticated/record/$recordId/edit/': {
      id: '/(app)/_authenticated/record/$recordId/edit/'
      path: '/record/$recordId/edit'
      fullPath: '/record/$recordId/edit/'
      preLoaderRoute: typeof appAuthenticatedRecordRecordIdEditIndexRouteImport
      parentRoute: typeof appAuthenticatedRouteRoute
    }
  }
}

interface appAuthenticatedRouteRouteChildren {
  appAuthenticatedMainIndexRoute: typeof appAuthenticatedMainIndexRoute
  appAuthenticatedNotificationsIndexRoute: typeof appAuthenticatedNotificationsIndexRoute
  appAuthenticatedPlannerIndexRoute: typeof appAuthenticatedPlannerIndexRoute
  appAuthenticatedProfileIndexRoute: typeof appAuthenticatedProfileIndexRoute
  appAuthenticatedRecordIndexRoute: typeof appAuthenticatedRecordIndexRoute
  appAuthenticatedTripCardsIndexRoute: typeof appAuthenticatedTripCardsIndexRoute
  appAuthenticatedNotificationsNotificationIdIndexRoute: typeof appAuthenticatedNotificationsNotificationIdIndexRoute
  appAuthenticatedPlannerDestinationIndexRoute: typeof appAuthenticatedPlannerDestinationIndexRoute
  appAuthenticatedPlannerExploreIndexRoute: typeof appAuthenticatedPlannerExploreIndexRoute
  appAuthenticatedPlannerGroupIndexRoute: typeof appAuthenticatedPlannerGroupIndexRoute
  appAuthenticatedPlannerInviteIndexRoute: typeof appAuthenticatedPlannerInviteIndexRoute
  appAuthenticatedPlannerProgressIndexRoute: typeof appAuthenticatedPlannerProgressIndexRoute
  appAuthenticatedProfileAccessibilityIndexRoute: typeof appAuthenticatedProfileAccessibilityIndexRoute
  appAuthenticatedProfileAchievementsIndexRoute: typeof appAuthenticatedProfileAchievementsIndexRoute
  appAuthenticatedProfileClaimIndexRoute: typeof appAuthenticatedProfileClaimIndexRoute
  appAuthenticatedProfileCountriesIndexRoute: typeof appAuthenticatedProfileCountriesIndexRoute
  appAuthenticatedProfileEditIndexRoute: typeof appAuthenticatedProfileEditIndexRoute
  appAuthenticatedProfileGuardiansIndexRoute: typeof appAuthenticatedProfileGuardiansIndexRoute
  appAuthenticatedProfileMapIndexRoute: typeof appAuthenticatedProfileMapIndexRoute
  appAuthenticatedProfileTravelPreferencesIndexRoute: typeof appAuthenticatedProfileTravelPreferencesIndexRoute
  appAuthenticatedRecordRecordIdIndexRoute: typeof appAuthenticatedRecordRecordIdIndexRoute
  appAuthenticatedRecordCalendarIndexRoute: typeof appAuthenticatedRecordCalendarIndexRoute
  appAuthenticatedRecordDeleteIndexRoute: typeof appAuthenticatedRecordDeleteIndexRoute
  appAuthenticatedRecordMapIndexRoute: typeof appAuthenticatedRecordMapIndexRoute
  appAuthenticatedRecordReportIndexRoute: typeof appAuthenticatedRecordReportIndexRoute
  appAuthenticatedRecordWriteIndexRoute: typeof appAuthenticatedRecordWriteIndexRoute
  appAuthenticatedSettingsNotificationsIndexRoute: typeof appAuthenticatedSettingsNotificationsIndexRoute
  appAuthenticatedTravelSelectIndexRoute: typeof appAuthenticatedTravelSelectIndexRoute
  appAuthenticatedTripCardsTripIdIndexRoute: typeof appAuthenticatedTripCardsTripIdIndexRoute
  appAuthenticatedTripCardsDeleteIndexRoute: typeof appAuthenticatedTripCardsDeleteIndexRoute
  appAuthenticatedTripCardsNewIndexRoute: typeof appAuthenticatedTripCardsNewIndexRoute
  appAuthenticatedRecordRecordIdEditIndexRoute: typeof appAuthenticatedRecordRecordIdEditIndexRoute
}

const appAuthenticatedRouteRouteChildren: appAuthenticatedRouteRouteChildren = {
  appAuthenticatedMainIndexRoute: appAuthenticatedMainIndexRoute,
  appAuthenticatedNotificationsIndexRoute:
    appAuthenticatedNotificationsIndexRoute,
  appAuthenticatedPlannerIndexRoute: appAuthenticatedPlannerIndexRoute,
  appAuthenticatedProfileIndexRoute: appAuthenticatedProfileIndexRoute,
  appAuthenticatedRecordIndexRoute: appAuthenticatedRecordIndexRoute,
  appAuthenticatedTripCardsIndexRoute: appAuthenticatedTripCardsIndexRoute,
  appAuthenticatedNotificationsNotificationIdIndexRoute:
    appAuthenticatedNotificationsNotificationIdIndexRoute,
  appAuthenticatedPlannerDestinationIndexRoute:
    appAuthenticatedPlannerDestinationIndexRoute,
  appAuthenticatedPlannerExploreIndexRoute:
    appAuthenticatedPlannerExploreIndexRoute,
  appAuthenticatedPlannerGroupIndexRoute:
    appAuthenticatedPlannerGroupIndexRoute,
  appAuthenticatedPlannerInviteIndexRoute:
    appAuthenticatedPlannerInviteIndexRoute,
  appAuthenticatedPlannerProgressIndexRoute:
    appAuthenticatedPlannerProgressIndexRoute,
  appAuthenticatedProfileAccessibilityIndexRoute:
    appAuthenticatedProfileAccessibilityIndexRoute,
  appAuthenticatedProfileAchievementsIndexRoute:
    appAuthenticatedProfileAchievementsIndexRoute,
  appAuthenticatedProfileClaimIndexRoute:
    appAuthenticatedProfileClaimIndexRoute,
  appAuthenticatedProfileCountriesIndexRoute:
    appAuthenticatedProfileCountriesIndexRoute,
  appAuthenticatedProfileEditIndexRoute: appAuthenticatedProfileEditIndexRoute,
  appAuthenticatedProfileGuardiansIndexRoute:
    appAuthenticatedProfileGuardiansIndexRoute,
  appAuthenticatedProfileMapIndexRoute: appAuthenticatedProfileMapIndexRoute,
  appAuthenticatedProfileTravelPreferencesIndexRoute:
    appAuthenticatedProfileTravelPreferencesIndexRoute,
  appAuthenticatedRecordRecordIdIndexRoute:
    appAuthenticatedRecordRecordIdIndexRoute,
  appAuthenticatedRecordCalendarIndexRoute:
    appAuthenticatedRecordCalendarIndexRoute,
  appAuthenticatedRecordDeleteIndexRoute:
    appAuthenticatedRecordDeleteIndexRoute,
  appAuthenticatedRecordMapIndexRoute: appAuthenticatedRecordMapIndexRoute,
  appAuthenticatedRecordReportIndexRoute:
    appAuthenticatedRecordReportIndexRoute,
  appAuthenticatedRecordWriteIndexRoute: appAuthenticatedRecordWriteIndexRoute,
  appAuthenticatedSettingsNotificationsIndexRoute:
    appAuthenticatedSettingsNotificationsIndexRoute,
  appAuthenticatedTravelSelectIndexRoute:
    appAuthenticatedTravelSelectIndexRoute,
  appAuthenticatedTripCardsTripIdIndexRoute:
    appAuthenticatedTripCardsTripIdIndexRoute,
  appAuthenticatedTripCardsDeleteIndexRoute:
    appAuthenticatedTripCardsDeleteIndexRoute,
  appAuthenticatedTripCardsNewIndexRoute:
    appAuthenticatedTripCardsNewIndexRoute,
  appAuthenticatedRecordRecordIdEditIndexRoute:
    appAuthenticatedRecordRecordIdEditIndexRoute,
}

const appAuthenticatedRouteRouteWithChildren =
  appAuthenticatedRouteRoute._addFileChildren(
    appAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  appAuthenticatedRouteRoute: appAuthenticatedRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
  publicLoginIndexRoute: publicLoginIndexRoute,
  publicPrivacyIndexRoute: publicPrivacyIndexRoute,
  publicSignUpIndexRoute: publicSignUpIndexRoute,
  publicAuthKakaoCallbackIndexRoute: publicAuthKakaoCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
