export { default as figmaHomeIcon } from './sidebar-home.svg'
export { default as figmaPlannerIcon } from './sidebar-planner.svg'
export { default as figmaRecordsIcon } from './sidebar-records.svg'
export { default as figmaProfileIcon } from './sidebar-profile.svg'
export { default as figmaRecordMapPhoto } from './record-map-photo.png'
export { default as figmaRecordMap } from './record-map.png'
export { default as figmaRecordDetail } from './record-detail.png'
export { default as figmaTripPlanning } from './trip-planning.jpeg'
