export const REQUIRED_NEW_API_CLIENTS = [
  'GET /api/profile/myInfo',
  'PUT /api/profile',
  'GET /api/profile/character',
  'GET /api/main/today-phrase',
  'GET /api/main/countries',
  'GET /api/main/weather',
  'GET /api/main/exchange-rate',
  'GET /api/main/search/popular',
  'GET /api/main/search/recent',
  'POST /api/main/search/recent',
  'DELETE /api/main/search/recent/{recentSearchId}',
  'GET /api/mission',
  'GET /api/mission/completed',
  'PATCH /api/mission/{missionId}',
] as const
